name: filechecksum
description: Desktop application to generate file hashes (checksum) for SHA and MD5 algorithms.
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  file_picker: ^5.2.2
  pixelarticons: ^0.4.0
  clipboard: ^0.1.3
  crypto: ^3.0.2
  url_launcher: ^6.1.6
  provider: ^6.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.10.0
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: Roboto Mono
      fonts:
        - asset: assets/fonts/RobotoMono-Regular.ttf
          style: normal
  assets:
    - assets/images/welcome.gif
    - assets/images/icon.png

flutter_icons:
  android: "launcher_icon"
  image_path: "assets/images/icon.png"
  min_sdk_android: 21
  windows:
    generate: true
    icon_size: 256
